version: '3.8'

services:
  php:
    build:
      context: .
    volumes:
      - ./public_home:/var/www/html/public_home
      - ./public_admin:/var/www/html/public_admin
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public_home:/var/www/html/public_home
      - ./public_admin:/var/www/html/public_admin
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge