services:
  php:
    build:
      context: .
    volumes:
      - ./public_home:/var/www/html/public_home
      - ./public_admin:/var/www/html/public_admin
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./public_home:/var/www/html/public_home
      - ./public_admin:/var/www/html/public_admin
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: baiplus_database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
