services:
  php:
    build:
      context: .
    volumes:
      - ./public_home:/var/www/html/public_home
      - ./public_admin:/var/www/html/public_admin
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./public_home:/var/www/html/public_home
      - ./public_admin:/var/www/html/public_admin
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: baiplus_database
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - .mysql_data/baiplus_final.sql:/docker-entrypoint-initdb.d/baiplus_final.sql
      - .mysql_data/baiplus_database.sql:/docker-entrypoint-initdb.d/baiplus_database.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge
